/* eslint-disable @typescript-eslint/no-unused-vars */
import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import cookieParser from 'cookie-parser';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import { z } from 'zod';
import { AuditLog, Product, Shop, User } from './models.js';
import { authenticate, requirePermission } from './middleware.js';
import { login, register } from './services/authService.js';
import { reviewApplication } from './services/shopService.js';
export const app = express();
app.use(helmet()); app.use(express.json()); app.use(cookieParser());
app.use(cors({ origin: process.env.FRONTEND_URL ?? 'http://localhost:3000', credentials: true }));
const authLimit = rateLimit({ windowMs: 15 * 60 * 1000, limit: 30 });
const setTokens = (res: express.Response, tokens: { access: string; refresh: string }) => { const base = { httpOnly: true, sameSite: 'lax' as const, secure: process.env.NODE_ENV === 'production' }; res.cookie('access_token', tokens.access, { ...base, maxAge: 900000 }); res.cookie('refresh_token', tokens.refresh, { ...base, maxAge: 604800000 }); };
app.get('/api/health', (_req, res) => res.json({ ok: true }));
app.post('/api/auth/register', authLimit, async (req, res, next) => { try { const input = z.object({ email: z.string().email().optional(), phone: z.string().optional(), password: z.string().min(8), fullName: z.string().min(2), role: z.enum(['client', 'partner']) }).parse(req.body); const user = await register(input); const tokens = await login(user.email!, input.password); setTokens(res, tokens); res.status(201).json({ user: tokens.user }); } catch (e) { next(e); } });
app.post('/api/auth/login', authLimit, async (req, res, next) => { try { const input = z.object({ email: z.string().email(), password: z.string() }).parse(req.body); const tokens = await login(input.email, input.password); setTokens(res, tokens); res.json({ user: tokens.user }); } catch (e) { res.status(401).json({ error: e instanceof Error ? e.message : 'Invalid credentials' }); } });
app.post('/api/auth/logout', (_req, res) => { res.clearCookie('access_token'); res.clearCookie('refresh_token'); res.status(204).end(); });
app.get('/api/auth/me', authenticate, (req, res) => res.json({ user: req.user }));
app.get('/api/catalog', async (req, res, next) => { try { const q = String(req.query.q ?? '').trim(); const filter: Record<string, unknown> = { status: 'ACTIVE' }; const shops = await Shop.find({ status: 'APPROVED' }).select('_id name slug'); filter.shopId = { $in: shops.map((s) => s._id) }; if (req.query.shopId) filter.shopId = req.query.shopId; if (req.query.minPrice || req.query.maxPrice) filter.price = { ...(req.query.minPrice ? { $gte: Number(req.query.minPrice) } : {}), ...(req.query.maxPrice ? { $lte: Number(req.query.maxPrice) } : {}) }; const query = q ? Product.find({ ...filter, $text: { $search: q } }) : Product.find(filter); const products = await query.sort(req.query.sort === 'price' ? { price: 1 } : { createdAt: -1 }).populate('shopId', 'name slug'); res.json({ products, shops }); } catch (e) { next(e); } });
app.get('/api/shops/:slug', async (req, res, next) => { try { const shop = await Shop.findOne({ slug: req.params.slug, status: 'APPROVED' }); if (!shop) return res.status(404).json({ error: 'Shop not found' }); const products = await Product.find({ shopId: shop._id, status: 'ACTIVE' }); res.json({ shop, products }); } catch (e) { next(e); } });
app.post('/api/partner/application', authenticate, requirePermission('shop:manage'), async (req, res, next) => { try { const input = z.object({ name: z.string().min(2), description: z.string().min(1), address: z.string().min(1), zone: z.enum(['Bab Bhar', 'Bab Jdid', 'Souk', 'Other']), phone: z.string().min(6), nationalIdNumber: z.string().min(1), commercialRegisterNumber: z.string().min(1), openingHours: z.array(z.object({ weekday: z.number(), opensAt: z.string(), closesAt: z.string(), isClosed: z.boolean() })).default([]) }).parse(req.body); const shop = await Shop.findOneAndUpdate({ ownerId: req.user._id }, { ...input, ownerId: req.user._id, slug: input.name.toLowerCase().replace(/[^a-z0-9]+/g, '-'), status: 'PENDING', rejectionReason: undefined }, { upsert: true, new: true }); res.json({ shop }); } catch (e) { next(e); } });
app.get('/api/partner/application', authenticate, requirePermission('shop:manage'), async (req, res, next) => { try { res.json({ shop: await Shop.findOne({ ownerId: req.user._id }) }); } catch (e) { next(e); } });
app.get('/api/admin/applications', authenticate, requirePermission('shop:approve'), async (_req, res, next) => { try { res.json({ shops: await Shop.find({ status: 'PENDING' }).populate('ownerId', 'email fullName') }); } catch (e) { next(e); } });
app.post('/api/admin/applications/:id/review', authenticate, requirePermission('shop:approve'), async (req, res, next) => { try { const input = z.object({ decision: z.enum(['APPROVED', 'REJECTED']), reason: z.string().optional() }).parse(req.body); const shop = await reviewApplication(String(req.params.id), req.user, input.decision, input.reason); await AuditLog.create({ actorId: req.user._id, action: `shop.${input.decision.toLowerCase()}`, entity: 'shop', entityId: shop._id, meta: { reason: input.reason } }); res.json({ shop }); } catch (e) { next(e); } });
app.get('/api/admin/dashboard', authenticate, requirePermission('shop:approve'), async (_req, res, next) => { try { const [pendingApplications, activeShops, totalUsers] = await Promise.all([Shop.countDocuments({ status: 'PENDING' }), Shop.countDocuments({ status: 'APPROVED' }), User.countDocuments()]); res.json({ pendingApplications, activeShops, totalUsers }); } catch (e) { next(e); } });
app.use((err: unknown, _req: express.Request, res: express.Response, _next: express.NextFunction) => res.status(400).json({ error: err instanceof Error ? err.message : 'Request failed' }));
